name: 'Setup Neo4j with APOC for testing'
description: 'Setup Neo4j with APOC for testing'
branding:
  icon: 'database'
  color: 'green'
inputs:
  tag:
    description: 'Version of Neo4j to use'
    required: false
    default: 'latest'
  password:
    description: 'The new password for the neo4j user'
    required: false
    default: 'ci'
runs:
  using: 'docker'
  image: 'Dockerfile'
